"""rename temparature to temperature

Revision ID: d4506b8f401f
Revises: 2774394def5c
Create Date: 2025-12-17 14:34:02.880622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4506b8f401f'
down_revision: Union[str, Sequence[str], None] = '2774394def5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('temperature', sa.Float(), nullable=False))
    op.drop_column('temperature', 'temparature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('temparature', sa.FLOAT(), nullable=False))
    op.drop_column('temperature', 'temperature')
    # ### end Alembic commands ###
